### ISSUE TITLE
Webpack error: module not found

### ISSUE THREAD

**Issue by phasetwenty** [AdventureLookup/adl-main#17]
When preparing a bundle, webpack exits with an error:

    ERROR in ./Scenes/Module/Components/ModuleCreature.jsx
    Module not found: Error: Can't resolve 'classnames/bind' in '/Users/chaverman/Workspace/adl-main/resources/assets/js/Scenes/Module/Components'
     @ ./Scenes/Module/Components/ModuleCreature.jsx 13:12-38
     @ ./Scenes/Module/ModuleDetail.jsx
     @ ./Scenes/Module/Module.jsx
     @ ./app.js

This prevents the whole app from running.

I have a PR inbound to resolve this

**Comment by harkenn** [comment]
Out of curiosity are you using yarn or just npm? What version of npm?

We don't have anything that uses classnames/bind; I expect the callstack for its use actually goes through react or one of the react- libraries that we use. I'll keep this ticket open until we can figure out exactly what's causing the issue and the ideal resolution.

**Comment by phasetwenty** [comment]
I was using `npm`, out of habit. I expect this issue to persist though as the import is made here: https://github.com/AdventureLookup/adl-main/blob/master/resources/assets/js/Scenes/Module/Components/ModuleCreature.jsx

**Comment by harkenn** [comment]
Ahhh of course. Thank you, no you're right. My original comment is wrong, clearly we do use the classNames library.

**Comment by harkenn** [comment]
Thanks!
