### ISSUE TITLE
Level information missing from module header

### ISSUE THREAD

**Issue by phasetwenty** [AdventureLookup/adl-main#19]
# Steps to reproduce

1. Visit any module page whose adventure includes level range information. In my dev environment, http://vagrant.adventurelookup.com/module/20 worked.
2. Notice the level information missing from the header:

<img width="821" alt="screenshot 2017-05-14 23 20 56" src="https://cloud.githubusercontent.com/assets/602819/26044905/1526fcae-38fc-11e7-8564-7f397ee7c03e.png">

I have a PR inbound to fix this issue.

**Comment by harkenn** [comment]
Based on the PR changes, this seems to occur specifically when one of either min_level or max_level has a value but not the other. In this instance the min/max level would be shown with a ? value for the other.
